---
datadog_api_key: "{{ lookup('env', 'DD_API_KEY') | default('YOUR_API_KEY_HERE', true) }}"
datadog_site: "datadoghq.com"
datadog_apm_enabled: true
datadog_logs_enabled: true
datadog_process_enabled: true
